export type Record = {
  accessionmethod: string;
  accessionyear: number;
  accesslevel: number;
  century: string;
  classification: string;
  classificationid: number;
  colorcount: number;
  colors: {
    color: string;
    css3: string;
    hue: string;
    percent: number;
    spectrum: string;
  }[];
  commentary: string;
  contact: string;
  contextualtextcount: number;
  creditline: string;
  culture: string;
  datebegin: number;
  dated: string;
  dateend: number;
  dateoffirstpageview: string;
  dateoflastpageview: string;
  department: string;
  description: string;
  dimensions: string;
  division: string;
  edition: string;
  exhibitioncount: number;
  groupcount: number;
  id: number;
  imagecount: number;
  imagepermissionlevel: number;
  images: {
    alttext: string;
    baseimageurl: string;
    copyright: string;
    date: string;
    description: string;
    displayorder: number;
    format: string;
    height: number;
    idsid: number;
    iiifbaseuri: string;
    imageid: number;
    publiccaption: string;
    renditionnumber: string;
    technique: string;
    width: number;
  }[];
  labeltext: string;
  lastupdate: string;
  lendingpermissionlevel: number;
  markscount: number;
  mediacount: number;
  medium: string;
  objectid: number;
  objectnumber: string;
  people: {
    alphasort: string;
    birthplace: string;
    culture: string;
    deathplace: string;
    displaydate: string;
    displayname: string;
    displayorder: number;
    gender: string;
    name: string;
    personid: number;
    prefix: string;
    role: string;
  }[];
  peoplecount: number;
  period: string;
  periodid: number;
  primaryimageurl: string;
  provenance: string;
  publicationcount: number;
  rank: number;
  relatedcount: number;
  seeAlso: {
    format: string;
    id: string;
    profile: string;
    type: string;
  }[];
  signed: string;
  standardreferencenumber: string;
  state: string;
  style: string;
  technique: string;
  techniqueid: number;
  title: string;
  titlescount: number;
  totalpageviews: number;
  totaluniquepageviews: number;
  url: string;
  verificationlevel: number;
  verificationleveldescription: string;
  worktypes: {
    worktype: string;
    worktypeid: string;
  }[];
};

export type HomepageRequest = {
  info: {
    next: string;
    page: number;
    pages: number;
    responsetime: string;
    totalrecords: number;
    totalrecordsperquery: number;
  };
  records: Record[];
};
