version: "3.9"
services:
  api:
    restart: always
    image: "art-archive-api"
    build: ./proxy
    ports:
      - "5000:5000"
    network_mode: "host"
    volumes:
      - type: bind
        source: ./proxy/.firebaseAdminSDK.json
        target: /usr/src/app/.firebaseAdminSDK.json
      - type: bind
        source: ./proxy/.env
        target: /usr/src/app/.env
  webapp:
    restart: always
    image: "art-archive-webapp"
    build: .
    ports:
      - "3000:3000"
    network_mode: "host"
    env_file:
      - path: .env.production
